[package]
name = "fluent-plugin-windows-evtx"
version = "0.1.0"
authors = ["dansedlacek <danfsedlacek@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
"chrono" = "0.4.6"
"evtx" = "0.3.0"
"helix" = "0.7.5"
